### ISSUE TITLE
[FEAT] 협업 초기 세팅

### ISSUE THREAD

**Issue by PgmJun** [DO-SOPT-SOPKATHON-TEAM-2th/server#1]
## Description 📝
협업 중 `git conflict` 를 방지하기 위한 공통 내용 기초 세팅

## To-Do ☑️
- [x] Entity 설계
- [x] MVC 3 Layered architecture (Controller, Service, Repository) 구현
- [x] 커스텀 예외 처리 로직 구현
- [x] 응답 형태 구현
